### ISSUE TITLE
Update authentication

### ISSUE THREAD

**Issue by mkosmala** [zooniverse/panoptes-subject-uploader#1]
@brian-c Could you update the authentication process for the uploader? I'm trying to use it on staging. It gets the auth token, but then I get a `Failed to sign in
[Error: You need to sign in or sign up before continuing.]` error.
GitHub says the last update was Mar 19, so I assume things have changed since then?

**Comment by CKrawczyk** [comment]
Just ran across the same issue today.  Is this an easy fix?

**Comment by CKrawczyk** [comment]
The issues seems to be on [this line](https://github.com/zooniverse/panoptes-subject-uploader/blob/master/lib/panoptes-subject-uploader.iced#L78), it should read:

``` js
await Panoptes.auth.signIn({login: args.username, password: args.password}).then(defer user).catch(console.error.bind console)
```

I will put together a pull request.

**Comment by srallen** [comment]
Authentication is broken, but for different reasons. Closing this in favor of #5.
