### ISSUE TITLE
Multi-image subject creation issues

### ISSUE THREAD

**Issue by srallen** [zooniverse/panoptes-subject-uploader#13]
If media is uploaded:
- [x] Subject IDs should only be added to the new ID array once but also only if all of the media files are successfully uploaded.

if media upload is skipped:
- [x] `skip-media-upload` option doesn't handle multi-image subjects. Current behavior is that a single row in the csv with multiple URLs will actually get parsed as X new subjects rather than X images on one subject. It also only adds the first column of URLs to the incorrect number of subjects created.
- [x] https check on the URL only checks the first column of URLs

I'll have a PR in soon to fix the first point. @simensta do you have time to look at the second two issues I found today?

**Comment by simensta** [comment]
@srallen, I can take a look at the second two issues today.

**Comment by srallen** [comment]
Fixed in #15
