### ISSUE TITLE
Error code 500 did not retry

### ISSUE THREAD

**Issue by CKrawczyk** [zooniverse/panoptes-subject-uploader#24]
I have a summer student who was using the subject uploader today and one of the subjects came back with and error code 500, but the code did not retry making the subject (as far as I can tell).  I was under the impression https://github.com/zooniverse/panoptes-subject-uploader/pull/21 would retry failed subjects.

As a side note, the images were already uploaded to the server (in a previous subject set) and he was using the `--skip-media-upload` flag with the existing URLs for the images.

**Comment by srallen** [comment]
@CKrawczyk Could you share the log file?

**Comment by srallen** [comment]
Just to clarify, it only reattempts up to 5 times. The `--skip-media-upload` parameter does one request when we check the URL to see if it is valid; I'd like to see the log if that was the point which had the 5 failures or if for some reason it didn't work as expected and just failed out right. If it worked as expected, and it failed after 5 times, then it's up to the person managing the subject upload to go through the logs, determine which subject failed, check if there's anything wrong (i.e. bad URL), and try again in another script run.

**Comment by CKrawczyk** [comment]
The exact log was

```
{"level":"info","message":"On row 989 of 1391","timestamp":"2016-06-29T11:18:05.111Z"}
{"level":"error","message":"!!! Error: Unexpected response code: 500","timestamp":"2016-06-29T11:18:06.139Z"}
```

The error only showed up once and the next line was processing row 990.  The URL on that line works just fine, and after a second try it uploaded without any problems.

**Comment by srallen** [comment]
It's possible the request to validate the URL failed 5 times... it only logs an error if it gets to that point. It doesn't log the attempts, though, perhaps it should? That would make debugging this more clear. I'm going to be uploading a bunch of subjects for a project here this next week I think, so I'll have lots of data to test with.

**Comment by CKrawczyk** [comment]
I agree, logging all 5 times would be very helpful.
