### ISSUE TITLE
Subject set numbers not accurate

### ISSUE THREAD

**Issue by trouille** [zooniverse/panoptes-subject-uploader#32]
![image002](https://cloud.githubusercontent.com/assets/4975655/18640982/383b850e-7e60-11e6-8536-b979c61352db.jpg)

**Comment by mcbouslog** [comment]
@marten - might this be related to the issue I have with the two NfN subject sets (#5923 and #5941)?

@trouille - sorry I know this might be a silly question, but just to confirm the subject set noted in your screen capture was uploaded via the panoptes-subject-uploader and not the Project Builder interface?

**Comment by trouille** [comment]
Yes, uploaded with the panoptes-subject-uploader. Not a silly question. I should have included that with the screen share. 

This was a screen capture shared with me by a Snapshot WI team member who is using the panoptes-subject-uploader to upload subjects. 

This is the code she used:
SET NODE_ENV=production
panoptes-subject-uploader ./ZooTest20160915Manifest.txt --username stengleinjl1 --password ******\* --project 2439 --workflow 1717 --subject-set 6025

**Comment by srallen** [comment]
This is a Panoptes issue, not with the uploader, so the issue should be opened there: https://github.com/zooniverse/Panoptes/issues. There's a sidekiq worker that determines/updates counts once subjects are uploaded and PFE uses these numbers to display.
