### ISSUE TITLE
Add error logging

### ISSUE THREAD

**Issue by srallen** [zooniverse/panoptes-subject-uploader#8]
Have the uploader create and write to an error log when one happens.

**Comment by srallen** [comment]
Several kinds of errors can occur while running the client. They should be investigated and correct handling or logging be added. Some should result in a reattempt. Failures delete the subject, but do nothing with successful uploaded images with multi-image subjects; should those images be deleted off of S3?

During the `PUT` request for subject images:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>D39F3DBDE488B347</RequestId><HostId>/Bzj2iOPAd0sHTL7Vl98JZzRlIQcujevtGbZADHZaMkLvL3w7yTozRGX7dX/NBvhSudDG/ohzTE=</HostId></Error>
```

```
{ [Error: getaddrinfo ENOTFOUND zooniverse-static.s3.amazonaws.com zooniverse-static.s3.amazonaws.com:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'zooniverse-static.s3.amazonaws.com',
  host: 'zooniverse-static.s3.amazonaws.com',
  port: 443 }
```

`{ [Error: socket hang up] code: 'ECONNRESET' }`

`{ [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }`

`{ [Error: read ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'read' }`

```
{ [Error: connect ETIMEDOUT 54.231.81.234:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '54.231.81.234',
  port: 443 }
```

When creating a subject

```
{ [Error: read ECONNRESET]
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read',
  response: undefined }
```

Error in the script:
`[TypeError: Cannot read property 'body' of undefined]`

**Comment by brian-c** [comment]
The body-of-undefined error should be fixed in more recent versions of panoptes-client.
